/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd.practica1;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import org.jdom2.Document;         // |
import org.jdom2.Element;          // |\ Librerías
import org.jdom2.JDOMException;    // |/ JDOM
import org.jdom2.input.SAXBuilder; // |
 import java.io.File;
import java.io.IOException;
import java.util.List;

/**
 *
 * @author Jorge Espina
 */

public class Principal extends javax.swing.JFrame {
    File archivos;
    JFileChooser seleccionado = new JFileChooser();
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desig Preview");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Jugar.png"))); // NOI18N
        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/LeerArchivo.png"))); // NOI18N
        jButton2.setText("Leer Archivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Tablero Tablero = new Tablero();
        Tablero.setVisible(true);
        IngresoJugadores Jugadores= new IngresoJugadores();
        Jugadores.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(seleccionado.showDialog(null, "Abrir Archivo") == JFileChooser.APPROVE_OPTION){
        archivos = seleccionado.getSelectedFile(); 
        
          SAXBuilder builder = new SAXBuilder();
          
        try
        {
        Document document = (Document) builder.build( archivos ); 
        Element rootNode = document.getRootElement(); 
       
        Element Raiz = document.getRootElement();
        
         List listpri = Raiz.getChildren("dimension");

            for (int i = 0; i < listpri.size(); i++) {
            Element camp = (Element) Raiz.getChildren("dimension").get(i);
            String Dimensiones = camp.getTextTrim();
            System.out.println( "Dimension :" + Dimensiones);
          
            }
        
        List list = rootNode.getChildren( "dobles" ); 
      
        for ( int i = 0; i < list.size(); i++ )        {
            Element scrabble = (Element) list.get(i); 
            List lista_dobles = scrabble.getChildren();
             System.out.println( "\tdobles" );
            for ( int j = 0; j < lista_dobles.size(); j++ )
            {
                Element dobles = (Element)lista_dobles.get( j );
                String x = dobles.getChildTextTrim("x");
                 String y = dobles.getChildTextTrim("y");
                System.out.println( "\t"+x+"\t\t"+y+"\t");
            }
        }
        
           List listtri = rootNode.getChildren( "triples" ); 
      
        for ( int i = 0; i < listtri.size(); i++ )        {
            Element scrabble = (Element) listtri.get(i); 
            List lista_triples = scrabble.getChildren();
             System.out.println( "\ttriples" );
            for ( int j = 0; j < lista_triples.size(); j++ )
            {
                Element triples = (Element)lista_triples.get( j );
               String x = triples.getChildTextTrim("x");
                String y = triples.getChildTextTrim("y");
                System.out.println( "\t"+x+"\t\t"+y+"\t");
            }
        }
        
            for ( int i = 0; i < rootNode.getChildren( "diccionario").size(); i++ ) {
            Element listd = (Element) rootNode.getChildren( "diccionario" ).get(i); 
            for (int j = 0; j < listd.getChildren().size(); j++) {
                Element diccionario = (Element)listd.getChildren("palabra").get( j );
                String palabra = (diccionario.getTextTrim());   
                System.out.println( "\t"+palabra+"\t");
                ListaSimpleFichasJugador ListaSimpleFichasJugador = new ListaSimpleFichasJugador();
                ListaSimpleFichasJugador.IngresarNodo(palabra);
                //ListaSimpleFichasJugador.VerLista();
            }
            }
  
       
            
            /*      List listdic = rootNode.getChildren( "diccionario" );
          for ( int j = 0; j < listdic.size(); j++ ) {
            Element scrabble = (Element) listdic.get(j); 
            List listd = scrabble.getChildren();
            for (int i = 0; i < listd.size(); i++) {
                 Element diccionario = (Element)listdic.get( i );
                String palabra = diccionario.getChildTextTrim("palabra");   
                System.out.println( "\t"+palabra+"\t");
                
                
            }
            }
            */
           
            
    }catch ( IOException | JDOMException io ) {
        System.out.println( io.getMessage() );
    }
               
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
